version: '3.8'

services:
  vps-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vps-personal-backend
    ports:
      - "${PORT:-8090}:8090"
    # Memuat semua environment variable dari file .env di host
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - horizon-network

networks:
  horizon-network:
    external: true
