spring:
  application:
    name: vps-personal-backend
  r2dbc:
    url: ${DATABASE_URL}
  sql:
    init:
      mode: always

grpc:
  client:
    channels:
      storage-node:
        address: static://localhost:9090
        negotiation-type: plaintext

jwt:
  access-token-expiry-hours: 24