spring:
  application:
    name: vps-personal-backend
  r2dbc:
    url: ${DATABASE_URL}
  sql:
    init:
      mode: always

  grpc:
    security:
      service-token: ${SERVICE_TOKEN}
    client:
      channels:
        storage-node:
          address: ${STORAGE_NODE_URL}
          negotiation-type: tls
          secure: false

jwt:
  access-token-expiry-hours: 1

server:
  port: 8090

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha