-- ============================================================
-- Schema H2 untuk unit testing (mode PostgreSQL compatibility)
-- Tidak mempengaruhi database PostgreSQL/Supabase produksi
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(255),
    email       VARCHAR(255) UNIQUE,
    password    VARCHAR(255),
    full_name   VARCHAR(255),
    avatar_url  VARCHAR(512),
    phone_number VARCHAR(50),
    storage_quota BIGINT DEFAULT 1073741824,
    is_active   BOOLEAN DEFAULT FALSE,
    migration_daily_limit INTEGER DEFAULT 3,
    migration_max_file_size BIGINT DEFAULT 268435456,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at  TIMESTAMP
);

CREATE TABLE IF NOT EXISTS roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS otp_verifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL,
    otp_code    VARCHAR(10) NOT NULL,
    type        VARCHAR(50) NOT NULL,
    expiry_time TIMESTAMP NOT NULL,
    verified    BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS refresh_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    token      VARCHAR(512) NOT NULL,
    revoked    BOOLEAN DEFAULT FALSE,
    expired_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS folders (
    id          UUID PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    parent_id   UUID REFERENCES folders(id) ON DELETE CASCADE,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS files (
    id                  UUID PRIMARY KEY,
    original_file_name  VARCHAR(512),
    storage_name        VARCHAR(512),
    size                BIGINT,
    user_id             BIGINT,
    provider            VARCHAR(50),
    external_account_id BIGINT,
    folder_id           UUID REFERENCES folders(id) ON DELETE SET NULL,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS upload_sessions (
    id              UUID PRIMARY KEY,
    file_id         UUID,
    temp_path       VARCHAR(1024),
    total_chunks    INT,
    uploaded_chunks INT DEFAULT 0,
    status          VARCHAR(50),
    completed_at    TIMESTAMP,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS download_sessions (
    id           UUID PRIMARY KEY,
    file_id      UUID,
    user_id      BIGINT,
    status       VARCHAR(50),
    total_bytes  BIGINT,
    bytes_sent   BIGINT DEFAULT 0,
    started_at   TIMESTAMP,
    completed_at TIMESTAMP,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS file_shared (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id     UUID NOT NULL,
    user_id     BIGINT,
    expires_at  TIMESTAMP,
    share_token VARCHAR(512),
    is_public   BOOLEAN DEFAULT FALSE,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS external_users (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL,
    provider         VARCHAR(50),
    provider_user_id VARCHAR(255),
    email            VARCHAR(255),
    access_token     VARCHAR(2048),
    refresh_token    VARCHAR(2048),
    expires_at       BIGINT
);

CREATE TABLE IF NOT EXISTS file_summaries (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id    UUID UNIQUE,
    summary    TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS folder_shared (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_id           VARCHAR(255) NOT NULL,
    folder_type         VARCHAR(50) NOT NULL,
    user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at          TIMESTAMP,
    share_token         VARCHAR(512) UNIQUE NOT NULL,
    permission          VARCHAR(50) DEFAULT 'VIEW',
    allow_anonymous     BOOLEAN DEFAULT TRUE,
    target_storage      VARCHAR(50) NOT NULL,
    external_account_id BIGINT REFERENCES external_users(id) ON DELETE SET NULL,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE files ADD COLUMN IF NOT EXISTS folder_id UUID REFERENCES folders(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS migration_tasks (
    id UUID PRIMARY KEY,
    batch_id UUID NOT NULL,
    user_id BIGINT NOT NULL,
    file_id UUID NOT NULL,
    file_name VARCHAR(255),
    source_provider VARCHAR(50) NOT NULL,
    target_provider VARCHAR(50) NOT NULL,
    target_external_account_id BIGINT,
    target_folder_id VARCHAR(255),
    delete_source BOOLEAN DEFAULT FALSE,
    status VARCHAR(50) NOT NULL,
    progress DOUBLE PRECISION DEFAULT 0.0,
    error_message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seed default roles
INSERT INTO roles (name) SELECT 'USER' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'USER');
INSERT INTO roles (name) SELECT 'ADMIN' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ADMIN');

CREATE TABLE IF NOT EXISTS academic_domains (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain VARCHAR(255) UNIQUE NOT NULL
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS academic_email VARCHAR(255) UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS student_verified BOOLEAN DEFAULT FALSE;

INSERT INTO academic_domains (domain) SELECT 'ac.id' WHERE NOT EXISTS (SELECT 1 FROM academic_domains WHERE domain = 'ac.id');
INSERT INTO academic_domains (domain) SELECT 'edu' WHERE NOT EXISTS (SELECT 1 FROM academic_domains WHERE domain = 'edu');
